// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cwYUiqL60aEgke1U13wNbQtfOU6mrEM',
    appId: '1:753158983953:web:90a86b50fbff1453453cb0',
    messagingSenderId: '753158983953',
    projectId: 'animalpedia-4f75b',
    authDomain: 'animalpedia-4f75b.firebaseapp.com',
    storageBucket: 'animalpedia-4f75b.appspot.com',
    measurementId: 'G-3Z1GTTZBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2F0J4S5fQFOpedCtgKnQLsff6o_dC0M',
    appId: '1:753158983953:android:22f8961d2d7bb6b3453cb0',
    messagingSenderId: '753158983953',
    projectId: 'animalpedia-4f75b',
    storageBucket: 'animalpedia-4f75b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjOX_A3oO6EJF6WHfX0QaE9L3M96LblUY',
    appId: '1:753158983953:ios:a2e0d946f0defc13453cb0',
    messagingSenderId: '753158983953',
    projectId: 'animalpedia-4f75b',
    storageBucket: 'animalpedia-4f75b.appspot.com',
    androidClientId: '753158983953-9btrbj00mm1jnjlcp2cbagv09fd5mlla.apps.googleusercontent.com',
    iosClientId: '753158983953-0enjlhjeruskmtneastqjl1b1cuv7bps.apps.googleusercontent.com',
    iosBundleId: 'com.solidevelectrosoft.adopals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjOX_A3oO6EJF6WHfX0QaE9L3M96LblUY',
    appId: '1:753158983953:ios:dff7304bf0910b03453cb0',
    messagingSenderId: '753158983953',
    projectId: 'animalpedia-4f75b',
    storageBucket: 'animalpedia-4f75b.appspot.com',
    androidClientId: '753158983953-9btrbj00mm1jnjlcp2cbagv09fd5mlla.apps.googleusercontent.com',
    iosClientId: '753158983953-jb3rptfpc4mlq1k6pe2clcesa3hiq892.apps.googleusercontent.com',
    iosBundleId: 'com.solidevelectrosoft.adopals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHKqFi-XBlBwgAr9q5S1jJgTPYlNv67Q8',
    appId: '1:753158983953:web:e3c77f82a0f1d83e453cb0',
    messagingSenderId: '753158983953',
    projectId: 'animalpedia-4f75b',
    authDomain: 'animalpedia-4f75b.firebaseapp.com',
    storageBucket: 'animalpedia-4f75b.appspot.com',
    measurementId: 'G-5PQ22388ZD',
  );
}
